### ISSUE TITLE
Miscellaneous routine todos before release

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#1497]
We only need to handle these right before release.

- [x] Update CI test dependency commits
  - RELEASE.md now says to do this as part of any release commit!
- [x] Update dates and authors in man pages
  - RELEASE.md now says to do this as part of any release commit!
- [ ] Update categorization of gbz80(5) instructions
  - e.g. `cpl` is an arithmetic/logic instruction, not a miscellaneous one
- [ ] Review section organization of man pages
  - e.g. rgbds(5) has an all-caps subheading "RPN EXPRESSIONS"

**Comment by Rangi42** [comment]
Document some of these as an initial step in RELEASE.md.
