### ISSUE TITLE
[Feature request] Some string function updates

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#625]
1. [x] Allow `STRCAT` to take any number of arguments (ideally even `STRCAT("hi") == "hi"` and `STRCAT() == ""`; this would also work well with `\#` from #596)
2. [ ] ~~Add `STRJOIN(sep, ...)` to concatenate all its arguments together joined by *sep* (so `STRJOIN(" - ", "ab", "cd", "ef") == "ab - cd - ef")`, and `STRJOIN("", ...) == STRCAT(...)`)~~
3. [ ] ~~Rename `STRIN` to `STRSTR` (this would match C's own `strstr`, and personally I keep reading `STRIN` as typo'd "`STRING`", not "`STR IN`")~~
4. [x] Add `STRRIN(str1, str2)` to get the last position of *str2* in *str1* (like C's `strrchr` vs `strchr`; this could be called `STRRSTR` if the `STRCHR` rename happens)
5. [ ] `STRFMT` (already discussed in #178; this would cover at least some use cases of #570 and #269)
6. [ ] Same format specifiers as `STRFMT` supported in `{symbol}` interpolation (already discussed in #570)

**Comment by ISSOtm** [comment]
I believe that `STRSTR` could be done by the user using `EQUS`, if they really want that.

**Comment by ISSOtm** [comment]
`STRCAT(\#)` wouldn't work, as the arguments wouldn't be separated by commas.

**Comment by Rangi42** [comment]
The proposal for `\#` was to separate the arguments with commas since that's how they're typed (undefined whether spaces would be after the commas). E.g. `mymacro "A", "B", "C"` where `mymacro` does `STRCAT(\#)` would produce `STRCAT("A", "B", "C")`.

**Comment by Rangi42** [comment]
`STRCAT` was updated, `STRRIN` was added, `STRJOIN` and the `STRSTR` rename were rejected, and `STRFMT` is covered by #178 and #570, so this is all covered.
